# Generated by Django 2.1.1 on 2018-10-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181001_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Category',
        ),
    ]
